classdef ComponentRegistry < handle
    % ComponentRegistry Store extensible definitions for supported UI factories.
    %   This handle class owns component types, permitted parents, creation
    %   arguments, editable property definitions, and extension metadata. It does
    %   not store component instances or document state.
    %
    %   Example:
    %       registry = macd.model.ComponentRegistry.createDefault();
    %       labelDefinition = registry.get("uilabel");

    properties (Access = private)
        Definitions containers.Map
        ParentContextRules macd.model.ParentContextRule = macd.model.ParentContextRule.empty
    end

    methods
        function obj = ComponentRegistry()
            % ComponentRegistry Create an empty data-driven component registry.
            arguments (Output)
                obj (1, 1) macd.model.ComponentRegistry
            end

            % Store definitions by factory without coupling the model to types.
            obj.Definitions = containers.Map("KeyType", "char", "ValueType", "any");
            obj.ParentContextRules = [macd.model.ParentContextRule.grid(); macd.model.ParentContextRule.absolute()];
        end

        function register(obj, definition)
            % register Add or replace one complete component definition.
            arguments (Input)
                obj (1, 1) macd.model.ComponentRegistry
                definition (1, 1) macd.model.ComponentDefinition
            end

            % Validate the lookup key before updating the registry atomically.
            key = char(definition.Factory);
            if isempty(key) || ~isvarname(key)
                error("macd:ComponentRegistry:InvalidFactory", ...
                    "Factory must be a valid MATLAB function name.");
            end
            obj.Definitions(key) = definition;
        end

        function result = contains(obj, factory)
            % contains Return true when a factory has a registered definition.
            arguments (Input)
                obj (1, 1) macd.model.ComponentRegistry
                factory string
            end
            arguments (Output)
                result (1, 1) logical
            end

            result = isKey(obj.Definitions, char(factory));
        end

        function definition = get(obj, factory)
            % get Return a registered component definition by factory name.
            arguments (Input)
                obj (1, 1) macd.model.ComponentRegistry
                factory string
            end
            arguments (Output)
                definition (1, 1) macd.model.ComponentDefinition
            end

            % Fail explicitly so callers cannot infer unsafe defaults.
            key = char(factory);
            if ~isKey(obj.Definitions, key)
                error("macd:ComponentRegistry:UnknownFactory", ...
                    "Component factory ""%s"" is not registered.", key);
            end
            definition = obj.Definitions(key);
        end

        function factories = listFactories(obj)
            % listFactories Return registered factory names in stable order.
            arguments (Input)
                obj (1, 1) macd.model.ComponentRegistry
            end
            arguments (Output)
                factories string
            end

            % Sorting makes palettes, tests, and generated output deterministic.
            factories = sort(string(keys(obj.Definitions)));
        end

        function name = displayName(obj, factory)
            % displayName Return the MATLAB documentation name for a factory.
            arguments (Input)
                obj (1, 1) macd.model.ComponentRegistry %#ok<INUSA>
                factory string
            end
            arguments (Output)
                name (1, 1) string
            end

            definition = obj.get(factory);
            name = definition.DisplayName;
        end

        function setParentContextRules(obj, rules)
            % setParentContextRules Replace the validated direct-parent rule set.
            arguments (Input)
                obj (1, 1) macd.model.ComponentRegistry
                rules macd.model.ParentContextRule
            end
            obj.ParentContextRules = rules(:);
        end

        function properties = getEffectiveProperties(obj, factory, parentFactory)
            % getEffectiveProperties Return supported properties for one direct parent context.
            arguments (Input)
                obj (1, 1) macd.model.ComponentRegistry
                factory (1, 1) string
                parentFactory (1, 1) string = ""
            end
            arguments (Output)
                properties macd.model.PropertyDefinition
            end

            % Remove legacy geometry before composing a direct-parent rule.
            definition = obj.get(factory);
            properties = definition.Properties;
            geometryPaths = ["Position", "Layout.Row", "Layout.Column"];
            if ~definition.IsRoot
                properties = properties(~ismember(string({properties.Path}), geometryPaths));
            end
            for index = 1:numel(obj.ParentContextRules)
                rule = obj.ParentContextRules(index);
                if ~rule.appliesTo(parentFactory), continue, end
                properties = properties(~ismember(string({properties.Path}), rule.SuppressedPaths));
                properties = [properties(:); rule.AddedProperties(:)]; %#ok<AGROW>
                break
            end
        end
    end

    methods (Static)
        function obj = createDefault()
            % createDefault Build the MATLAB R2024 standard component registry.
            arguments (Output)
                obj (1, 1) macd.model.ComponentRegistry
            end

            % Define reusable parent and property groups for standard UI entries.
            obj = macd.model.ComponentRegistry();
            figureChildren = ["uifigure", "uipanel", "uigridlayout", ...
                "uitab", "uibuttongroup"];
            gridChildren = [figureChildren, "uitabgroup"];
            common = ["Position", "Visible", "Enable", "Tooltip", "Tag"];
            layout = ["Layout.Row", "Layout.Column"];
            numeric = [common, "Value", "Limits", layout];

            % Register the figure and layout containers first for deterministic use.
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uifigure", "matlab.ui.Figure", strings(1, 0), true, {}, ...
                ["Position", "Visible", "Name"], struct("DisplayName", "UI Figure", "Category", "Figure")));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uigridlayout", "matlab.ui.container.GridLayout", ...
                ["uifigure", "uipanel", "uigridlayout", "uitab", "uibuttongroup"], false, {}, ...
                ["Position", "Visible", "RowHeight", "ColumnWidth", ...
                "Padding", "RowSpacing", "ColumnSpacing"], struct("DisplayName", "Grid Layout", "Category", "Container")));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uipanel", "matlab.ui.container.Panel", figureChildren, false, {}, ...
                [common, "Title", "TitlePosition", "BorderType", layout], ...
                struct("DisplayName", "Panel", "Category", "Container")));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uitabgroup", "matlab.ui.container.TabGroup", figureChildren, false, {}, ...
                [common, "SelectedTab", layout], struct("DisplayName", "Tab Group", "Category", "Container")));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uitab", "matlab.ui.container.Tab", "uitabgroup", false, {}, ...
                [common, "Title", "Icon", layout], struct("DisplayName", "Tab", "Category", "Container")));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uibuttongroup", "matlab.ui.container.ButtonGroup", figureChildren, false, {}, ...
                [common, "Title", "SelectedObject", layout], struct("DisplayName", "Button Group", "Category", "Container")));

            % Register common interactive components and their supported styles.
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uilabel", "matlab.ui.control.Label", gridChildren, false, {}, ...
                [common, "Text", "HorizontalAlignment", "VerticalAlignment", layout], ...
                struct("DisplayName", "Label", "Category", "Common")));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uibutton", "matlab.ui.control.Button", gridChildren, false, {}, ...
                [common, "Text", "Icon", "ButtonPushedFcn", layout], ...
                struct("DisplayName", "Button", "Category", "Common", "OverlayShape", "roundedRectangle", "SupportedStyles", ...
                ["push", "state"], "DefaultStyle", "push", ...
                "DeclaredTypesByStyle", struct("push", "matlab.ui.control.Button", ...
                "state", "matlab.ui.control.StateButton"))));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uicheckbox", "matlab.ui.control.CheckBox", gridChildren, false, {}, ...
                [common, "Text", "Value", "ValueChangedFcn", layout], ...
                struct("DisplayName", "Check Box", "Category", "Common")));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uicolorpicker", "matlab.ui.control.ColorPicker", gridChildren, false, {}, ...
                [common, "Value", "ValueChangedFcn", layout], ...
                struct("DisplayName", "Color Picker", "Category", "Common", "Introduced", "R2024a")));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uidatepicker", "matlab.ui.control.DatePicker", gridChildren, false, {}, ...
                [common, "Value", "DisplayFormat", "ValueChangedFcn", layout], ...
                struct("DisplayName", "Date Picker", "Category", "Common")));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uidropdown", "matlab.ui.control.DropDown", gridChildren, false, {}, ...
                [common, "Value", "Items", "ItemsData", "Editable", ...
                "ValueChangedFcn", layout], struct("DisplayName", "Drop-down", "Category", "Common")));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uieditfield", "matlab.ui.control.EditField", gridChildren, false, {}, ...
                [common, "Value", "ValueChangedFcn", layout], ...
                struct("DisplayName", "Edit Field", "Category", "Common", "SupportedStyles", ["text", "numeric"], ...
                "NumericProperties", ["Limits", "RoundFractionalValues", "ValueDisplayFormat"], ...
                "DefaultStyle", "text")));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uihyperlink", "matlab.ui.control.Hyperlink", gridChildren, false, {}, ...
                [common, "Text", "URL", "VisitedColor", layout], struct("DisplayName", "Hyperlink", "Category", "Common")));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uiimage", "matlab.ui.control.Image", gridChildren, false, {}, ...
                [common, "ImageSource", "ScaleMethod", "ImageClickedFcn", layout], ...
                struct("DisplayName", "Image", "Category", "Common")));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uilistbox", "matlab.ui.control.ListBox", gridChildren, false, {}, ...
                [common, "Value", "Items", "ItemsData", "Multiselect", ...
                "ValueChangedFcn", layout], struct("DisplayName", "List Box", "Category", "Common")));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uiradiobutton", "matlab.ui.control.RadioButton", "uibuttongroup", false, {}, ...
                [common, "Text", "Value", "ValueChangedFcn", layout], ...
                struct("DisplayName", "Radio Button", "Category", "Common")));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uislider", "matlab.ui.control.Slider", gridChildren, false, {}, ...
                [numeric, "Orientation", "MajorTicks", "MinorTicks", "Step", ...
                "ValueChangedFcn", "ValueChangingFcn"], struct("DisplayName", "Slider", "Category", "Common", "OverlayShape", "slider", ...
                "SupportedStyles", ["slider", "range"], "DefaultStyle", "slider", ...
                "ResizeConstraint", "fixedHeight", ...
                "DeclaredTypesByStyle", struct("slider", "matlab.ui.control.Slider", ...
                "range", "matlab.ui.control.RangeSlider"))));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uispinner", "matlab.ui.control.Spinner", gridChildren, false, {}, ...
                [numeric, "Step", "ValueChangedFcn", layout], struct("DisplayName", "Spinner", "Category", "Common")));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uitable", "matlab.ui.control.Table", gridChildren, false, {}, ...
                [common, "Data", "ColumnName", "ColumnEditable", "ColumnFormat", ...
                "RowName", "CellEditCallback", layout], struct("DisplayName", "Table", "Category", "Common")));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uitextarea", "matlab.ui.control.TextArea", gridChildren, false, {}, ...
                [common, "Value", "ValueChangedFcn", layout], struct("DisplayName", "Text Area", "Category", "Common")));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uitogglebutton", "matlab.ui.control.ToggleButton", ...
                "uibuttongroup", false, {}, [common, "Text", "Value", layout], ...
                struct("DisplayName", "Toggle Button", "Category", "Common")));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uitree", "matlab.ui.container.Tree", gridChildren, false, {}, ...
                [common, "Root", "SelectedNodes", "SelectionChangedFcn", layout], ...
                struct("DisplayName", "Tree", "Category", "Common", "SupportedStyles", ["default", "checkbox"], ...
                "DefaultStyle", "default")));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uitreenode", "matlab.ui.container.TreeNode", ...
                ["uitree", "uitreenode"], false, {}, ["Text", "NodeData", "Checked", ...
                "Icon", "ContextMenu"], struct("DisplayName", "Tree Node", "Category", "Common", ...
                "RequiresParentComponent", true)));

            % Register axes, including programmatic-only axes supported by App Designer.
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uiaxes", "matlab.ui.control.UIAxes", gridChildren, false, {}, ...
                [common, "XLim", "YLim", "XLabel", "YLabel", "Title", layout], ...
                struct("DisplayName", "UI Axes", "Category", "Axes", "OverlayShape", "axes")));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "axes", "matlab.graphics.axis.Axes", gridChildren, false, {}, ...
                ["Position", "Visible", "XLim", "YLim", layout], ...
                struct("DisplayName", "Axes", "Category", "Axes", "ProgrammaticOnly", true)));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "geoaxes", "matlab.graphics.axis.GeographicAxes", gridChildren, false, {}, ...
                ["Position", "Visible", "LatitudeLimits", "LongitudeLimits", layout], ...
                struct("DisplayName", "Geographic Axes", "Category", "Axes", "ProgrammaticOnly", true)));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "polaraxes", "matlab.graphics.axis.PolarAxes", gridChildren, false, {}, ...
                ["Position", "Visible", "ThetaLim", "RLim", layout], ...
                struct("DisplayName", "Polar Axes", "Category", "Axes", "ProgrammaticOnly", true)));

            % Register instrumentation components and their style variants.
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uigauge", "matlab.ui.control.Gauge", gridChildren, false, {}, ...
                [common, "Value", "Limits", "MajorTicks", "MinorTicks", layout], ...
                struct("DisplayName", "Gauge", "Category", "Instrumentation", "OverlayShapesByStyle", ...
                struct("circular", "circle", "linear", "rectangle", "ninetydegree", "circle", "semicircular", "circle"), "SupportedStyles", ...
                ["circular", "linear", "ninetydegree", "semicircular"], ...
                "DefaultStyle", "circular", "ResizeConstraint", "aspectRatio", ...
                "DeclaredTypesByStyle", struct( ...
                "circular", "matlab.ui.control.Gauge", ...
                "linear", "matlab.ui.control.LinearGauge", ...
                "ninetydegree", "matlab.ui.control.NinetyDegreeGauge", ...
                "semicircular", "matlab.ui.control.SemicircularGauge"))));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uiknob", "matlab.ui.control.Knob", gridChildren, false, {}, ...
                [common, "Value", "Items", "Limits", "MajorTicks", "MinorTicks", "ValueChangedFcn", layout], ...
                struct("DisplayName", "Knob", "Category", "Instrumentation", "OverlayShape", "circle", "SupportedStyles", ...
                ["continuous", "discrete"], "DefaultStyle", "continuous", ...
                "ResizeConstraint", "aspectRatio", "DeclaredTypesByStyle", ...
                struct("continuous", "matlab.ui.control.Knob", ...
                "discrete", "matlab.ui.control.DiscreteKnob"))));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uilamp", "matlab.ui.control.Lamp", gridChildren, false, {}, ...
                [common, "Color", layout], struct("DisplayName", "Lamp", "Category", "Instrumentation", "OverlayShape", "circle", ...
                "ResizeConstraint", "aspectRatio")));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uiswitch", "matlab.ui.control.Switch", gridChildren, false, {}, ...
                [common, "Value", "Items", "ValueChangedFcn", layout], ...
                struct("DisplayName", "Switch", "Category", "Instrumentation", "OverlayShape", "switch", "SupportedStyles", ...
                ["slider", "rocker", "toggle"], "DefaultStyle", "slider", ...
                "ResizeConstraint", "aspectRatio", "DeclaredTypesByStyle", ...
                struct("slider", "matlab.ui.control.Switch", ...
                "rocker", "matlab.ui.control.RockerSwitch", ...
                "toggle", "matlab.ui.control.ToggleSwitch"))));

            % Register figure tools and HTML as programmatic UI components.
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uihtml", "matlab.ui.control.HTML", gridChildren, false, {}, ...
                [common, "HTMLSource", "HTMLEditor", "Data", "HTMLEventReceivedFcn", layout], ...
                struct("DisplayName", "HTML", "Category", "Extensible")));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uicontextmenu", "matlab.ui.container.ContextMenu", ...
                ["uifigure", "uipanel", "uitab", "uibuttongroup"], false, {}, ...
                ["Visible", "Position"], struct("DisplayName", "Context Menu", "Category", "FigureTools")));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uimenu", "matlab.ui.container.Menu", ["uifigure", "uimenu"], false, {}, ...
                ["Text", "Checked", "Separator", "Enable", "Visible", "MenuSelectedFcn"], ...
                struct("DisplayName", "Menu", "Category", "FigureTools", "RequiresParentComponent", true)));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uitoolbar", "matlab.ui.container.Toolbar", "uifigure", false, {}, ...
                ["Visible", "HandleVisibility"], struct("DisplayName", "Toolbar", "Category", "FigureTools")));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uipushtool", "matlab.ui.container.toolbar.PushTool", "uitoolbar", false, {}, ...
                ["CData", "Tooltip", "Separator", "ClickedCallback", "Visible", ...
                "Enable"], struct("DisplayName", "Push Tool", "Category", "FigureTools", ...
                "RequiresParentComponent", true)));
            obj.register(macd.model.ComponentDefinition.fromPaths( ...
                "uitoggletool", "matlab.ui.container.toolbar.ToggleTool", "uitoolbar", false, {}, ...
                ["CData", "Tooltip", "Separator", "OnCallback", "OffCallback", ...
                "State", "Visible", "Enable"], struct("DisplayName", "Toggle Tool", "Category", "FigureTools", ...
                "RequiresParentComponent", true)));
        end
    end
end

%{
MatlabAppClassDesigner - Data-driven registry of supported UI components.
Copyright (C) 2026 MatlabAppClassDesigner contributors

This file is part of MatlabAppClassDesigner.

MatlabAppClassDesigner is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

MatlabAppClassDesigner is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with MatlabAppClassDesigner. If not, see <https://www.gnu.org/licenses/>.
%}
